name: Development

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      run: npm install
      env:
        CI: false
    - name: Build page
      run: npm run build
    - name: Archive development artifacts
      uses: actions/upload-artifact@v1
      with:
        name: ami-frontend-dev
        path: ami-frontend-dev
